# Generated by Django 5.2.14 on 2026-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='concepts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
